### ISSUE TITLE
(-)-exclude flag

### ISSUE THREAD

**Issue by planetmija** [hillu/local-log4j-vuln-scanner#20]
There is a "problem" with excluding paths in Linux (maybe intended, but then needs to be added to help):

Usage can be:
[-]-exclude[=]/path/to/exclude
[-]-exclude[=]/path/to/exclude/*
What does not work is:
[-]-exclude[=]/path/to/exclude/      # when path ends with "/" is not excluded (often when auto-completion is used)

Help is not clear as well:

  -exclude value
    	path**s** to exclude

Actually it is only one path_ but you can specify exclude multiple times.

BTW: Thanks for the scanner!

**Comment by planetmija** [comment]
Not related to exclude, but minor formatting issue.

Output needs new line:

"no such file or **directoryindicator** for vulnerable component found in"
"no such file or **directorycan**'t open"

If I should open a new issue for that, just say so.

**Comment by martin-schlossarek** [comment]
https://github.com/hillu/local-log4j-vuln-scanner/pull/22 should fix the problem with trailing slashes
