### ISSUE TITLE
Scanner cannot find vulnerabilites when class is esclazz 

### ISSUE THREAD

**Issue by ccoltx** [hillu/local-log4j-vuln-scanner#25]
There is at least one library which shades log4j, packaging the class as `.esclazz`. I have no idea why.

https://github.com/elastic/apm-agent-java

Can we add scanning support for these files?

**Comment by hillu** [comment]
What the…
Are there more extensions the tool should be aware of?

**Comment by disasmwinnie** [comment]
What the... indeed.

```
    /**
     * The class file of {@code IndyBootstrapDispatcher}, loaded from classpath resource, {@code esclazz} extension avoids
     * being loaded as a regular class.
     */
  ```
  
  via https://github.com/elastic/apm-agent-java/commit/55ad185755813358fc92fa436e7515b4a49104f7#diff-2ec63f545539ff7d65f52ef01087a18c7cdd9eb7130de156fb412ae6fe9e580eR177
  
  
  At the moment I don't see this being a general problem. ``esclazz`` does not seem to be a J9 JVM specific extension. Searching the topic I only find the apm-agent-repo you mentioned.
  
  Does anybody out there have a different view on this issue?

**Comment by ccoltx** [comment]
Thanks for the quick fix. I will test once we have a new release.
