### ISSUE TITLE
Can't read magic from JAR file member

### ISSUE THREAD

**Issue by sjquinney** [hillu/local-log4j-vuln-scanner#29]
With the latest version of the tool I am getting lots of warning messages to STDOUT (not STDERR) like these. Does the tool need to warn about not being able to read magic?

can't read magic from JAR file member: /opt/android-studio/lib/batik-codec-1.12.0-8.jar (org/apache/batik/ext/awt/image/codec/properties): EOF
can't read magic from JAR file member: /opt/android-studio/lib/istack-commons-runtime-3.0.7.jar (.gitkeep): EOF
can't read magic from JAR file member: /opt/android-studio/lib/resources_en.jar (fileTemplates/internal/CMakeLists.txt.cmake.ft): EOF
can't read magic from JAR file member: /opt/android-studio/lib/spellchecker.jar (com/intellij/spellchecker/excluded.dic): EOF
can't read magic from JAR file member: /opt/android-studio/lib/tips-intellij-idea-community-193.4.jar (tips/bundle.version): EOF
can't read magic from JAR file member: /opt/android-studio/lib/xmlpull-1.1.3.1.jar (XMLPULL_1_1_3_1_VERSION): EOF
can't read magic from JAR file member: /opt/android-studio/lib/xpp3_min-1.1.4c.jar (XPP3_1.1.4c_MIN_VERSION): EOF

**Comment by paulerickson** [comment]
I get this output even with the `--quiet` flag
