### ISSUE TITLE
New magic number check failure

### ISSUE THREAD

**Issue by Ghepardo** [hillu/local-log4j-vuln-scanner#36]
Hi

Using release 0.9, the scanner is now giving very many "can't read magic from JAR file member" messages.  This did not happen in release 0.8.1.  I'm not sure that the fix that went into 0.9 is working as you intended.  

Kind regards.

**Comment by hillu** [comment]
Can you provide more details or one of the affected files itself?

**Comment by hillu** [comment]
oh, nevermind, I forgot to push the 0.9.1 tag I had prepared.
