### ISSUE TITLE
[Feature Request] Arm64 build in releases

### ISSUE THREAD

**Issue by KittyBorgX** [hillu/local-log4j-vuln-scanner#4]
Adding a workflow for arm64 build for m1 macs and other arm64 devices

**Comment by mwunderlich** [comment]
I can confirm that the tool doesn't run on an M1 Mac. It fails with the following msg: 
```
./log4j-vuln-finder.go: line 1: package: command not found
./log4j-vuln-finder.go: line 3: syntax error near unexpected token `newline'
./log4j-vuln-finder.go: line 3: `import ('
```

Mac OS Version 11.6 "Big Sur"
Go Version go1.17.5 darwin/amd64

The script also fails to execute using the specific arm64 build of Go version 1.16beta1, downloaded from here: 
https://go.dev/dl/#go1.16beta1

**Comment by KittyBorgX** [comment]
@mwunderlich Can you try running `go build` first and then running the executable? 
The problem for me is that: 
- After downloading from the releases page, my mac couldnt run it as it was built on an ubuntu machine
- Arm64 builds are different and releasing a separate build for arm is capable of running on an m1 mac

**Comment by mwunderlich** [comment]
@KittyBorgX This works! After running `go build`, I am able to run the resulting file `local-log4j-vuln-scanner`. 
Thanks a lot.

**Comment by hillu** [comment]
Glad you got it working. Closing the issue.
