### ISSUE TITLE
How to use filter.go

### ISSUE THREAD

**Issue by natschel** [hillu/local-log4j-vuln-scanner#45]
With Windows 10, running "go run main.go `<filepath`>" (within scanner) does well.
With Windows 10, running "go run main.go -help" (within scanner) does well.
With Windows 10, running "go run filter.go" fails with "package command-line-arguments is not a main package".
With Windows 10, running "go run filter.go -help" fails with "package command-line-arguments is not a main package".
Pardon I'm a newbie. Any hints?

**Comment by hillu** [comment]
Please refer to the ["build from source"](https://github.com/hillu/local-log4j-vuln-scanner#building-from-source) bit in the README.

**Comment by hillu** [comment]
@natschel Did this help?

**Comment by natschel** [comment]
Yes, I got it, Thanks.

________________________________
Von: Hilko Bengen ***@***.***>
Gesendet: Donnerstag, 23. Dezember 2021 13:18
An: hillu/local-log4j-vuln-scanner
Cc: natschel; Mention
Betreff: Re: [hillu/local-log4j-vuln-scanner] How to use filter.go (Issue #45) 

@natschel Did this help?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hillu** [comment]
thanks for the feedback. Closing the issue then.
