### ISSUE TITLE
Just curious - why do you do f.Seek(0, END) twice?

### ISSUE THREAD

**Issue by dladlk** [hillu/local-log4j-vuln-scanner#47]
I am new in GoLang but anyway not sure if it is done by intention :)

https://github.com/hillu/local-log4j-vuln-scanner/blob/4d8a362bb3a8050b213f319ca5280a2a5f7b6bad/scanner/main.go#L163

**Comment by hillu** [comment]
I suppose that my intent may have been to seek back to the start of the file, but this is pointless because `handleJar` does not use the file pointer at all (it only uses the `ReaderAt` interface.)
