### ISSUE TITLE
installation with go install

### ISSUE THREAD

**Issue by vitikyalapatii** [hillu/local-log4j-vuln-scanner#57]
Could you please add a feature to install the scanner using  "go install" ?

eg:
go  install  github.com/hillu/local-log4j-vuln-scanner@latest

**Comment by hillu** [comment]
I have no idea what you would want to achieve here … and how to do it.

**Comment by dreamcat4** [comment]
well i have been able to `go install` both cmdline tools individually like this:

```sh
go install "github.com/hillu/local-log4j-vuln-scanner/scanner"
go install "github.com/hillu/local-log4j-vuln-scanner/patcher"
```

but the only thing is that you called these binary executables just simply by generic names only `scanner` and `patcher`. So there is nothing in that to indicate what they are meant to be scanning for, or patching for. So having to find that again on your `$PATH` is pretty sadface :(

Maybe start them with `log4j-` something? Would probably be a better choice. For the shell autocomplete to pick them up.
