### ISSUE TITLE
Scanning of a directory ending .war leads in an error

### ISSUE THREAD

**Issue by karstenlehmann** [hillu/local-log4j-vuln-scanner#6]
If the tool scan a directory which ends with ".war" it seems that the program handle the directory as zipped file (and tries to extract the file).
The result is an error output like "the handle is invalid"

**Comment by allixus** [comment]
Can confirm. I get this output trying to scan my application:

```
cant't open JAR file: C:\path\to\app\build\libs\app-0.0.1-SNAPSHOT.war (size 95502423): zip: not a valid zip file
Scan finished
```

**Comment by hillu** [comment]
Good catch! Thanks.
